### ISSUE TITLE
예시코드 작성하기

### ISSUE THREAD

**Issue by l2hyunwoo** [bookmaru/MARU-Android#15]
- [x] Navigation Component 의존성 추가
- [x] HomeFragment 추가
- [x] Activity/Fragment에 Hilt 설정
- [x] ViewModel, Repository, DataSource 클래스 만들고 ViewModel, Repository 의존성 설정
- [x] RepositoryModule, DataSource 모듈 만들기
