### ISSUE TITLE
(모임생성, RV) SearchFragment, CreateMoimFragment

### ISSUE THREAD

**Issue by sery270** [bookmaru/MARU-Android#21]
## Output
<img width="784" alt="스크린샷 2021-03-12 오전 12 03 00" src="https://user-images.githubusercontent.com/59532818/110807368-4fddbf00-82c6-11eb-88f8-bcfe6ab4d3af.png">

## WHY
#20 참고

## TODO

- [x] 검색 화면 : SearchFragment
  - [x] 검색 전 화면 : SearchBeforeFragment
    - [x] 최근 검색어 아이템 : item_recent
  - [x] 검색 후 화면 : SearchAfterFragment
    - [x] 책 검색 결과 아이템 : item_book_result
    - [x] 검색 결과 아이템 : item_moim_result
- [x] SerachAfterRecyclerview
