### ISSUE TITLE
Project Setting

### ISSUE THREAD

**Issue by l2hyunwoo** [bookmaru/MARU-Android#9]
- [x] gitignore 설정
- [x] build.gradle.kts 설정
- [x] buildSrc 모듈에서 dependency 설정
- [x] Github Action CI/CD 도입
- [x] 슬랙봇 apk 구우는거(?) 연결
- [x] base/util 패키지에 필요한 기능 추가
- [x] ktlint 설정
